name: Compress Images

on:
  push:
    paths:
      - '**.png'
      - '**.webp'
      - '**.jpg'
      - '**.jpeg'

jobs:
  compress:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      attestations: write
      id-token: write
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
      - uses: ximplez/action-tinify@master
        with:
          api_key: ${{ secrets.TINIFY_API_KEY }}
          commit_message: ${{ github.event.head_commit.message }}
